name: Rails Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.1.2
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - name: Build and test with Rake
        env:
          RAILS_ENV: test
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rubocop
          bundle exec rails_best_practices
          bundle exec rails bundle-audit
          bundle exec rails brakeman
          bundle exec rails test
