---
description: Generated sheet for ifconfig
tags:
- community
shortcuts:
- default:
  - 'To display network settings of an interface:': "ifconfig <interface>\n\n"
  - 'To display all interfaces, even if down:': "ifconfig -a\n\n"
  - 'To take down / up the wireless adapter:': "ifconfig wlan0 {up|down} \n\n"
  - 'To set a static IP and netmask:': "ifconfig eth0 192.168.1.100 netmask 255.255.255.0\n\n"
  - 'You may also need to add a gateway IP:': 'route add -net 192.168.1.0 netmask
      255.255.255.0 gw 192.168.1.1

      '
