---
:description: Generated sheet for iwconfig
:tags:
- community
- networking
:shortcuts:
  :defaults:
    'To display wireless settings of the first wireless adapter:': "iwconfig wlan0\n\n"
    'To take down / up the wireless adapter:': "iwconfig wlan0 txpower {on|auto|off}\n\n"
    'To change the mode of the wireless adapter:': 'iwconfig wlan0 mode {managed|ad-hoc|monitor}

      '
